### ISSUE TITLE
bug: the label 'distance' will concatenate to the previous one

### ISSUE THREAD

**Issue by lzhengp1986** [ITU-R-Study-Group-3/ITU-R-HF#17]
https://github.com/ITU-R-Study-Group-3/ITU-R-HF/blob/c48c60bbf986a3f0d550691d1f9c803e638cf17e/ITURHFProp/Src/ITURHFProp/Report.c#L443
while running the .exe with option -c, the label 'distance' will concatenate to the previous one.

**Comment by jawatson** [comment]
Many thanks for reporting this - I've just committed a fix.
